version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3400:3400"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3300:3300"
    environment:
      - VITE_API_URL=http://backend:3400
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
